// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MTG.Models;
using System;

namespace MTG.Migrations
{
    [DbContext(typeof(MTGContext))]
    [Migration("20180617182521_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MTG.Models.Card", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Artist");

                    b.Property<string>("Border");

                    b.Property<float?>("Cmc");

                    b.Property<string>("ColorIdentity");

                    b.Property<string>("Colors");

                    b.Property<string>("Flavor");

                    b.Property<int?>("Hand");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Layout");

                    b.Property<int?>("Life");

                    b.Property<string>("Loyalty");

                    b.Property<string>("ManaCost");

                    b.Property<int?>("MultiverseId");

                    b.Property<string>("Name");

                    b.Property<string>("Names");

                    b.Property<string>("Number");

                    b.Property<string>("OriginalText");

                    b.Property<string>("OriginalType");

                    b.Property<string>("Power");

                    b.Property<string>("Printings");

                    b.Property<string>("Rarity");

                    b.Property<string>("ReleaseDate");

                    b.Property<bool?>("Reserved");

                    b.Property<string>("Set");

                    b.Property<string>("SetName");

                    b.Property<string>("Source");

                    b.Property<bool?>("Starter");

                    b.Property<string>("SubTypes");

                    b.Property<string>("SuperTypes");

                    b.Property<string>("Text");

                    b.Property<bool?>("Timeshifted");

                    b.Property<string>("Toughness");

                    b.Property<string>("Type");

                    b.Property<string>("Types");

                    b.Property<string>("Variations");

                    b.Property<string>("Watermark");

                    b.HasKey("Id");

                    b.ToTable("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
